name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.0.0"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run-name: lint & format
      - run: |
          pushd server
          gleam deps download
          gleam test
          gleam format --check src test
          popd
          pushd client
          gleam deps download
          gleam test
          gleam format --check src test
          popd
